### ISSUE TITLE
Spleef

### ISSUE THREAD

**Issue by samuelap1324** [Herobrinedobem/HEventos#4]
To fazendo um server na 1.7.10 e ate agora o unico evento que eu tive problemas foi o spleef quando executo o comando para iniciar ele me manda essa mensagem (An internal erro ocurred while attempting to perform this command)o bowspleef e a minamortal tbm estão com o mesmo problema

**Comment by samuelap1324** [comment]
server command: /evento iniciar spleef true
[19:00:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'evento' in plugin HEventos v1.6.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1517.168]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1517.168]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:718) ~[CraftServer.class:1.7.10-1517.168]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1328) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1110) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException: One/both of the worlds is/are null!
	at me.herobrinedobem.heventos.utils.Cuboid.<init>(Cuboid.java:29) ~[?:?]
	at me.herobrinedobem.heventos.eventos.Spleef.<init>(Spleef.java:35) ~[?:?]
	at me.herobrinedobem.heventos.Comandos.onCommand(Comandos.java:169) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1517.168]
	... 13 more
[19:00:56] [Server thread/INFO]: CONSOLE issued server command: /list 
[19:00:56] [Server thread/INFO]: Ha 1 de no maximo 20 jogadores online.
[19:00:56] [Server thread/INFO]: default: Samuelap13
[19:01:28] [Server thread/INFO]: CONSOLE issued server command: /list 
[19:01:28] [Server thread/INFO]: Ha 1 de no maximo 20 jogadores online.
[19:01:28] [Server thread/INFO]: default: Samuelap13
[19:02:00] [Server thread/INFO]: CONSOLE issued server command: /list 
[19:02:00] [Server thread/INFO]: Ha 1 de no maximo 20 jogadores online.
[19:02:00] [Server thread/INFO]: default: Samuelap13
[19:02:32] [Server thread/INFO]: CONSOLE issued server command: /list 
[19:02:32] [Server thread/INFO]: Ha 1 de no maximo 20 jogadores online.
[19:02:32] [Server thread/INFO]: default: Samuelap13
[19:02:36] [Server thread/INFO]: Samuelap13 issued server command: /evento iniciar spleef true
[19:02:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'evento' in plugin HEventos v1.6.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1517.168]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1517.168]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:718) ~[CraftServer.class:1.7.10-1517.168]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1328) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1110) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException: One/both of the worlds is/are null!
	at me.herobrinedobem.heventos.utils.Cuboid.<init>(Cuboid.java:29) ~[?:?]
	at me.herobrinedobem.heventos.eventos.Spleef.<init>(Spleef.java:35) ~[?:?]
	at me.herobrinedobem.heventos.Comandos.onCommand(Comandos.java:169) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1517.168]
	... 13 more
[19:03:04] [Server thread/INFO]: CONSOLE issued server command: /list 
[19:03:04] [Server thread/INFO]: Ha 1 de no maximo 20 jogadores online.
[19:03:04] [Server thread/INFO]: default: Samuelap13
[19:03:23] [Server thread/INFO]: LIXEIRO: Os itens serão removidos do chão em 60 segundos!

**Comment by samuelap1324** [comment]
ja resolvi por algum motivo o server não carregou o mundo que eu tinha setado os evento ai ele deu esse erro
